### ISSUE TITLE
The library consumes over 600 mb of memory

### ISSUE THREAD

**Issue by RainbowInHell** [XamlAnimatedGif/WpfAnimatedGif#106] opened 2024-10-03 17:08 UTC
https://github.com/user-attachments/assets/108eece0-913a-421b-8e8d-e275a350ab63

**Comment by thomaslevesque** [comment] 2024-10-03 17:22
Hi @RainbowInHell,

This is a duplicate of [many other issues](https://github.com/XamlAnimatedGif/WpfAnimatedGif/issues?q=is%3Aissue+is%3Aclosed+memory). It's a known problem that I'm not going to fix, because it's inherent to the way this library works. I made another library, [XamlAnimatedGif](https://github.com/XamlAnimatedGif/XamlAnimatedGif), whose goal was specifically to reduce memory usage (at the cost of higher CPU usage).

**Closed as completed by thomaslevesque** 2024-10-03 17:22 UTC
