### ISSUE TITLE
Huge memory consumption

### ISSUE THREAD

**Issue by gundone** [XamlAnimatedGif/WpfAnimatedGif#103] opened 2023-06-05 19:33 UTC
The application loads a 6Mb Gif and the memory consumption increases from 100Mb to 1.3Gb.

**Comment by thomaslevesque** [comment] 2023-06-06 00:46
Hi @gundone,

This is a duplicate of [many other issues](https://github.com/XamlAnimatedGif/WpfAnimatedGif/issues?q=is%3Aissue+is%3Aclosed+memory). It's a known problem that I'm not going to fix, because it's inherent to the way this library works. I made another library, [XamlAnimatedGif](https://github.com/XamlAnimatedGif/XamlAnimatedGif), whose goal was specifically to reduce memory usage (at the cost of higher CPU usage).

That being said, if you have a 6MB GIF, you should probably consider converting it to a video...

**Closed as completed by thomaslevesque** 2023-06-06 00:46 UTC
