### ISSUE TITLE
NullReferenceException Windows XP - v1.4.12

### ISSUE THREAD

**Issue by hawelo** [XamlAnimatedGif/WpfAnimatedGif#13] opened 2015-01-26 08:48 UTC
Hi,
I'm getting following exception on Windows XP SP3 with the version 1.4.12:

System.NullReferenceException: Object reference not set to an instance of an object.
at WpfAnimatedGif.ImageBehavior.GetQueryOrDefault[T](BitmapMetadata metadata, String query, T defaultValue)
at WpfAnimatedGif.ImageBehavior.GetFullSize(BitmapDecoder decoder, GifFile gifMetadata)
at WpfAnimatedGif.ImageBehavior.GetAnimation(Image imageControl, BitmapSource source)
at WpfAnimatedGif.ImageBehavior.InitAnimationOrImage(Image imageControl)
at WpfAnimatedGif.ImageBehavior.ImageControlLoaded(Object sender, RoutedEventArgs e)
...

It works well on Windows Vista,7 and 8.1.

**Comment by thomaslevesque** [comment] 2015-01-26 09:06
That's weird... on Windows XP, `BitmapDecoder.Metadata` normally returns null for a GIF image, which causes the library to fall back to manual metadata decoding. So in `GetFullSize` you shouldn't reach the part where `GetQueryOrDefault` is called. Apparently in your case `BitmapDecoder.Metadata` does *not* return null, but still doesn't contain the expected information... I'll have to look into it.

Do you have WIC (Windows Imaging Component) installed on this machine? Or any other software that would affect the behavior of image decoding?

In the meantime, you can try to use [XamlAnimatedGif](https://github.com/thomaslevesque/XamlAnimatedGif), a new library that does almost the same thing but doesn't rely on WPF image decoding (it's still in alpha, though)

**Comment by hawelo** [comment] 2015-01-26 09:18
Thank you for your reply.
The machine has a clean installation of WinXP SP3 with installed .NET Framework 4 + installed WMP 11 (could that affect the image decoding?)

The problem with the new XamlAnimatedGif is that it supports only .NET Framework 4.5 which is not supported on WinXP SP3.

**Comment by thomaslevesque** [comment] 2015-01-26 09:35
> The problem with the new XamlAnimatedGif is that it supports only .NET Framework 4.5 which is not supported on WinXP SP3.

Ah, yes, forgot about that... I intend to backport it to 4.0, but it's not done yet.

I haven't been able to reproduce the issue in a WinXP SP3 VM... Are you seeing the problem with all GIF images, or only some of them? In the latter case, can you please provide the affected images?

I also pushed a [branch with a possible fix](https://github.com/thomaslevesque/WpfAnimatedGif/tree/issue13), but since I can't reproduce the problem, I can't test the fix... Can you try to build this branch and see if it fixes the problem for you? If it does, I will merge it and publish a new version.

**Comment by hawelo** [comment] 2015-01-26 10:13
The possible fix did not help. 

I'm connecting to the XP machine via Remote Desktop. Maybe that's also relevant information.

I've tried several GIFs and the problem is with all of them. For example with this one:
![red-siren-animated](https://cloud.githubusercontent.com/assets/10705630/5898072/ec82fb68-a54b-11e4-935b-f9afcf1ad583.gif)

**Comment by thomaslevesque** [comment] 2015-01-26 11:08
For me this image works fine on XP SP3. I also installed WMP 11, and tried to connect via remote desktop, but I still can't repro.

> The possible fix did not help. 

OK, so perhaps the problem isn't where I thought... Are you sure you built the branch with the fix, not master? (it's easy to clone the repo and forget to checkout the branch, I know it happened to me before...)

**Comment by thomaslevesque** [comment] 2015-01-26 11:09
Also, can you try with `m.ContainsQuery("/logscrdesc/Width")` instead of `m.ContainsQuery("/logscrdesc")`?

**Comment by hawelo** [comment] 2015-01-26 11:26
I've checked the sources and the problem is in the GetFullSize method where decoder.Metadata is null. The question is how this can happen (problem in GetDecoder method?).

**Comment by hawelo** [comment] 2015-01-26 11:39
The GetDecoder method goes to following block and returns decoder with decoder.Metadata==null
```
BitmapFrame frame = image as BitmapFrame;
if (frame != null)
{
    decoder = frame.Decoder;
    Uri.TryCreate(frame.BaseUri, frame.ToString(), out uri);
}
```

**Comment by hawelo** [comment] 2015-01-26 11:55
So it looks that WIC does not support GIF metadata in XP and Vista:
https://social.msdn.microsoft.com/Forums/vstudio/en-US/e766a323-8b3e-4b5b-9e98-6f998f168f26/imagesourcemetadata-is-null-for-gif-images-on-windows-xp-works-fine-on-windows-7?forum=wpf

**Comment by thomaslevesque** [comment] 2015-01-26 12:41
> The GetDecoder method goes to following block and returns decoder with decoder.Metadata==null

Actually, I think the problem is that it doesn't enter the last `if` block in the `GetDecoder` method. Since `CanReadNativeMetadata` clearly returns false in this case, this leaves us with only one option: `decoder is GifBitmapDecoder` is false... but I don't understand how that's possible. Can you check the type of the decoder?

> So it looks that WIC does not support GIF metadata in XP and Vista:

Yes, I know. That's why I re-implemented GIF metadata decoding to handle this case (all the classes in the WpfAnimatedGif.Decoding namespace). The problem here is that it doesn't correctly fall back to custom decoding.

**Comment by hawelo** [comment] 2015-01-26 12:52
It does enter the last if block, but the last block doesn't modify the decoder.Metadata property so it will stay null.

**Comment by thomaslevesque** [comment] 2015-01-26 13:02
> It does enter the last if block

Oh I see. So I guess both `stream` and `uri` are null?
How are you setting the `ImageBehavior.AnimatedSource` property in your app? Does the demo app work on this machine?

> but the last block doesn't modify the decoder.Metadata property so it will stay null.

It's not supposed to (the `Metadata` property is read-only), but it should set the `gifFile` out parameter.

**Comment by thomaslevesque** [comment] 2015-01-26 13:05
> How are you setting the `ImageBehavior.AnimatedSource` property in your app?

More specifically: what is the actual type of the value you assign to the property? It will only work with `BitmapImage` or `BitmapFrame` (and its derived classes of course).

**Comment by hawelo** [comment] 2015-01-26 13:16
I've tried the demo and it works on that machine so the problem is with the way I set the AnimatedSource property.
I have a byte array with the content of GIF. This is how I'm setting it:

```
using (var memoryStream = new MemoryStream())
{
    memoryStream.Write(data, 0, data.Length);
    memoryStream.Seek(0, SeekOrigin.Begin);

   var frame = BitmapFrame.Create(memoryStream, BitmapCreateOptions.None, BitmapCacheOption.OnLoad);
   ImageBehavior.SetAnimatedSource(image, frame);
}
```
I've also tried following (this GIF is defined as Content and copied with the application):
```
<Image wag:ImageBehavior.AnimatedSource="200w.gif"  />
```

**Comment by thomaslevesque** [comment] 2015-01-26 16:05
OK, I think I understand what's going on, at least in the first case.

- In the first case, you're creating a `BitmapFrame` from a stream; so in `GetDecoder`, we can't get the URI (since there isn't one), and the stream used to create the `BitmapFrame` is not accessible either. Since I need either the stream or the URI to read the metadata manually, it can't possibly work... So this scenario (setting the `AnimatedSource` to a `BitmapFrame` on Windows XP) is clearly not supported. This is a bug, because it doesn't detect that it needs to fall back to custom decoding, and doesn't detect that it can't. It should at least throw an exception in that case.

    Note that if you're doing it from code-behind, you can use a `BitmapImage` instead of a `BitmapFrame`, and it should work fine.

- In the second case, I would have expected it to work; when you specify an `ImageSource` in XAML in XAML via an URI, the actual type is `BitmapFrameDecode`, which is a subclass of `BitmapFrame`, and whose `ToString` method returns the URI. It usually works fine if you set the build action to Resource, or if you set it to Content and copy it to the output folder (with the same relative path). actually, you can test this in the demo app: just pick the image named `siteoforigin.gif`. It has the build action set to Content and is copied to the output folder.

**Comment by hawelo** [comment] 2015-01-27 07:47
> Note that if you're doing it from code-behind, you can use a BitmapImage instead of a BitmapFrame, and it should work fine.

In this case, I need to hold the MemoryStream open, otherwise, I will get an exception when reading the metadata. I could solve this problem by saving the GIF to the file system and creating the BitmapImage with specified UriSource. This works well on all systems.

**Comment by thomaslevesque** [comment] 2015-01-27 10:33
> In this case, I need to hold the MemoryStream open, otherwise, I will get an exception when reading the metadata

Well, depending on when and how you load the image, it could work even if you close the stream. If you use CacheOption = OnLoad, and set the AnimatedSource when the image control is loaded, it should work fine. But this solution is a bit brittle...

> I could solve this problem by saving the GIF to the file system and creating the BitmapImage with specified UriSource. This works well on all systems.

Yes, this is probably your safest bet.

**Closed** 2015-11-07 22:04 UTC
