### ISSUE TITLE
Cannot find Resource, when uppercase letter in path

### ISSUE THREAD

**Issue by HekMe** [XamlAnimatedGif/WpfAnimatedGif#52] opened 2018-08-23 09:49 UTC
Ahoy,
i've found bug where, you get System.IO.IOException resource not found, when your path to gif contains uppercase letter( in both XAML and code).
I've made the directory and gif lowercase as workaround, but i would be fancy, if you change this one thing ;)

Thanks.

**Comment by thomaslevesque** [comment] 2018-08-23 11:33
Also, it might sound like a stupid theory, but is it possible that your folder name was "lmages" (with a lowercase `L` instead of an uppercase `I` ?)

**Comment by thomaslevesque** [comment] 2018-08-23 11:34
Anyway, I'm not able to reproduce the issue. I might be able to if you provide more details.

**Comment by raiderruler** [comment] 2019-05-10 19:16
I was just able to reproduce this myself. I pulled down the NuGet package and referenced my gif in Visual Studio like so:
<Image gif:ImageBehavior.AnimatedSource="Resources/loading.gif" />

If I changed it to lower case r for resources directory, then it worked. I'd gladly help if I can give you more details.

Visual Studio 2017
Target Framework 4.6
Using in a C# DLL project\Assembly (not the actual WPF application project)
gif is in a Resources folder.

**Comment by thomaslevesque** [comment] 2019-05-11 13:57
@raiderruler I'm still unable to repro. I tried with various combinations (lower/upper case in the file name or directory, lower/upper case in the AnimatedSource path), and it always works fine. Could you provide a project that exhibits the issue?

**Comment by raiderruler** [comment] 2019-05-11 22:24
Strange, I cannot reproduce it now when I switch it back and forth from Resources to resources. If I get it to happen again somehow, I'll let you know.

**Comment by thomaslevesque** [comment] 2019-05-12 20:26
I'm closing this for now, I'll reopen if someone can find a reliable way to reproduce the issue.

**Closed by thomaslevesque** 2019-05-12 20:26 UTC

**Comment by raiderruler** [comment] 2019-05-12 21:36
The strange thing is that I was originally getting that exception when I was in the office on Friday. That's what made me look for a reason why it was happening and I found this thread. When I tried from home with the same source code, I couldn't reproduce it. I'll check again from my office PC again tomorrow.
